language: node_js
node_js:
  - "0.10"
  - "0.11"
before_script:
  - npm install -g karma bower
  - bower install
after_success:
  - npm run coveralls
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"